[DA] 뿌리기 등록화면 작업 2️⃣
mash-up-kr/GGiriGGiri-iOS pull request #110
Opened 2022-08-09 06:04 UTC by dvHuni

# 개요
- 🔗  이슈링크 : resolve #100 

# 변경사항

## 작업 내용

https://github.com/mash-up-kr/GGiriGGiri_iOS/pull/108  작업에 이은 뿌리기 등록화면 작업입니다.

* b8d1a8641503122a003cc4f684714442320d3a40 커밋에서 data가 오지않는 response에 대한 base를 추가하여 분기처리 하였습니다.
    * API를 추가하는 작업을 진행한 경우 해당 커밋을 cherrypick 해주시길 부탁드립니다. (@kimkyunghun3 , @ios-h)
* 0a321a9e798946f12b69c755e7cc3a042bf40413 커밋에서 기존의 `DDIPInputfield`, `DDIPInputView`가 입력한 text에 대한 binding이 없어 추가하였습니다.
* 46666e5e529d299374cbc87b9c6071d3bff6c773 커밋에서 뿌리기 등록 API 연동을 진행했습니다. 다만 테스트 영상의 경우 mock 데이터가 내려오므로 실제 연동은 다시 한번 확인할 필요가 있습니다.
* 4a3b6d840281ef4ad8a0327e2967033acdceb3f1 커밋에서 DDIPToastView에 대한 케이스를 추가하였습니다.
* 4af507dec0a72fde8284e99bcf372178eff556d2 커밋에서 뿌리기 등록 API에 대한 결과 toast를 띄우는 기능을 추가하였습니다.

### 미리보기

작업 후

https://user-images.githubusercontent.com/39300449/183575968-37a47932-612f-4830-a746-3fef4ed23ebb.mp4

2022-08-09 11:08 UTC, ios-h submitted a review, later dismissed
고생하셨습니다아👍👍

2022-08-09 12:18 UTC, ios-h approved these changes

2022-08-09 14:08 UTC, kimkyunghun3 requested changes
고생했숩니다!!

2022-08-09 14:08 UTC, kimkyunghun3 commented on Projects/App/Sources/Driver/Networking/ResponseModel/BaseResponseModel.swift
> +struct BaseResponseModel: Decodable {
궁금한게 Mock에서 Data가 nil인데 이부분은 안넣어도 괜찮은건가요?

2022-08-09 14:08 UTC, kimkyunghun3 commented on Projects/App/Sources/Driver/Service/GifticonAPI.swift
> +    var headers: HTTPHeaders {
이렇게 헤더 처리하려고 위에 extension 만든거군요 ! 아주좋아요 ㅎㅎ

2022-08-09 14:08 UTC, kimkyunghun3 commented on Projects/App/Sources/Register/RegisterGifticonViewController.swift
> +    private func updateValidate(_ isValidate: Bool) {
몬가 제 눈에는 동사 두개같은데 의도가있는건가요?

2022-08-09 14:08 UTC, kimkyunghun3 commented on Projects/App/Sources/Register/RegisterGifticonViewController.swift
> +    private func showRegisterSuccessToast() {
뒤에 ToastView라고 해주면 더 좋을거같습니다!

2022-08-09 14:08 UTC, kimkyunghun3 commented on Projects/App/Sources/Register/RegisterGifticonViewController.swift
> +    private func showRegisterSuccessToast() {
아 아니면 파악이 가능해서 toast라고 하신건가요?!

2022-08-09 14:08 UTC, kimkyunghun3 commented on Projects/App/Sources/Register/RegisterGifticonViewModel.swift
> +        case deadLineMinute(String?)
```suggestion
        case deadlineMinute(String?)
```
하나의 단어라서 Line이라고 안하셔도 댈거같습니다!

2022-08-09 15:27 UTC, dvHuni commented
해당 이슈들 모두 이슈 남겨두고 머지 후 이후 수정하겠습니다. cc. @kimkyunghun3

2022-08-09 15:27 UTC, kimkyunghun3 approved these changes

2022-08-09 15:27 UTC, merged

2022-08-10 06:51 UTC, dvHuni commented on Projects/App/Sources/Driver/Networking/ResponseModel/BaseResponseModel.swift
> +struct BaseResponseModel: Decodable {
넵, 넣지않아도 됩니다! 작성된 property에 대해서만 decode를 시도합니다

2022-08-10 06:51 UTC, dvHuni commented on Projects/App/Sources/Register/RegisterGifticonViewController.swift
> +    private func updateValidate(_ isValidate: Bool) {
수정하겠습니다 😓

2022-08-10 06:51 UTC, dvHuni commented on Projects/App/Sources/Register/RegisterGifticonViewModel.swift
> +        case deadLineMinute(String?)
수정하겠습니다 😄