[DA] 마이박스 응모 BOX 카드 탭 이벤트 구현 및 탭바 이슈 수정
mash-up-kr/GGiriGGiri-iOS pull request #155
Opened 2022-08-16 17:09 UTC by ios-h

# 개요
- 🔗  이슈링크 : resolve https://github.com/mash-up-kr/GGiriGGiri_iOS/issues/142

# 변경사항

## 💻 작업 내용
- 결과 확인 > 결과 확인 페이지로 이동. 결과 확인 버튼 enable. 이후 결과 확인 버튼은 해당 결과로 바뀌어야함. (당첨 또는 꽝)
- 꽝 > 꽝 버튼은 disable. 카드 클릭 시 꽝 페이지 이동
- 당첨 > 당첨 버튼은 disable. 카드 클릭 시 당첨 페이지 이동
- 응모 중 > 응모 중 버튼은 disable. 카드 클릭 시 디테일 페이지 이동
- 탭 바 스크롤 문제 수정

## 📱 스크린샷
<img width="563" alt="스크린샷 2022-08-17 오전 2 08 46" src="https://user-images.githubusercontent.com/95578975/184938193-a465fb85-4557-4e21-974d-76be664c8254.png">

2022-08-17 01:09 UTC, kimkyunghun3 requested changes
고생했습니다!

2022-08-17 01:09 UTC, kimkyunghun3 commented on Projects/App/Sources/MyBox/MyBoxListCollectionViewDelegate.swift
> +    var id: Int = 0
요거 id는 변하는건가요?

2022-08-17 01:09 UTC, kimkyunghun3 commented on Projects/App/Sources/MyBox/View/MyBoxView.swift
> +import RxRelay
조금 사소할수 있지만 통일성을 위해 S위에 R이 있으면 좋을거같네요!

2022-08-17 01:09 UTC, kimkyunghun3 commented on Projects/App/Sources/MyBox/MyBoxListCollectionViewDelegate.swift
> +    var id: Int = 0
그리고 이거 외부에서 접근해야하나요?

2022-08-17 07:28 UTC, dvHuni requested changes

2022-08-17 07:28 UTC, dvHuni commented on Projects/App/Sources/MyBox/MyBoxListCollectionViewDelegate.swift
> +        if data.count == 0 { return }
어떤 이유에서 해당 코드로 오류가 수정이 되는걸까요?

2022-08-17 07:28 UTC, dvHuni commented on Projects/App/Sources/Result/ResultViewController.swift
> +        guard let imageUrl = URL(string: "https://item.kakaocdn.net/do/e27878b2d7c30103f76bfb73833ffaab9f17e489affba0627eb1eb39695f93dd") else { return }
이미지 URL이 테스트 하면서 넣어둔 URL로 올려진것 같습니다.

확인 부탁드립니다 😓

2022-08-17 14:10 UTC, dvHuni commented on Projects/App/Sources/MyBox/View/MyBoxListCollectionViewCell.swift
> +    private var disposable: Disposable?
cell 재사용시 dispose 시켜주는것은 올바른 방향이나,

binding 해야하는것이 많아진다면 DisposeBag을 통해 Binding된 모든 내용을 dispose 시켜야 reuse시 문제가 발생하지 않습니다! 

[참고자료](https://makeeyaf.postype.com/post/9014926)

@kimkyunghun3 , @ios-h

2022-08-17 14:10 UTC, dvHuni approved these changes, later dismissed

2022-08-17 14:29 UTC, kimkyunghun3 commented on Projects/App/Sources/MyBox/View/MyBoxListCollectionViewCell.swift
> +    private var disposable: Disposable?
좋은 정보 감사합니다..! 일단은 하나라서 저렇게 할 수 있지만, 추후에 더 생긴다면 disposeBag으로 바꾸겠습니다!
RxSwift에서 자주 생기는 에러인거 같아서 잘 적어두겠습니다 :)

2022-08-17 14:32 UTC, kimkyunghun3 commented on Projects/App/Sources/MyBox/View/MyBoxView.swift
> +import RxRelay
수정했습니다!

2022-08-17 14:32 UTC, kimkyunghun3 commented on Projects/App/Sources/MyBox/MyBoxListCollectionViewDelegate.swift
> +    var id: Int = 0
요거 안써서 지우고 접근제어가 필요한거 다 넣었습니다!

2022-08-19 09:28 UTC, ios-h commented on Projects/App/Sources/MyBox/MyBoxListCollectionViewDelegate.swift
> +        if data.count == 0 { return }
현재 응모 BOX에서만 카드 클릭 시 다음 화면으로 이동하고, 등록 BOX는 터치 이벤트가 없습니다. 그래서 MyCollectionViewDataSource에서 type이 `applied`일 경우에만 data를 넣어주고 있고, 등록 BOX의 경우 data를 넣어주고 있지 않기 때문에 이 시점에서의 data 수가 0이기 때문에 저렇게 처리를 했었습니다! 근데 굳이 data수로 체크하기보다, type이 registered일 경우 return을 하는 게 더 좋을 것 같네요! [여기](https://github.com/mash-up-kr/GGiriGGiri_iOS/commit/f4e73d650aaa963c32d08387498cb1e32993c4b1)서 수정했습니다!

2022-08-19 09:29 UTC, ios-h commented on Projects/App/Sources/MyBox/MyBoxListCollectionViewDelegate.swift
> +        if data.count == 0 { return }
현재 응모 BOX에서만 카드 클릭 시 다음 화면으로 이동하고, 등록 BOX는 터치 이벤트가 없습니다. 그래서 MyCollectionViewDataSource에서 type이 `applied`일 경우에만 data를 넣어주고 있고, 등록 BOX의 경우 data를 넣어주고 있지 않기 때문에 이 시점에서의 data 수가 0이여서 저렇게 처리를 했었습니다! 근데 굳이 data수로 체크하기보다, type이 `registered`일 경우 return을 하는 게 더 좋을 것 같네요! [여기](https://github.com/mash-up-kr/GGiriGGiri_iOS/commit/f4e73d650aaa963c32d08387498cb1e32993c4b1)서 수정했습니다!

2022-08-19 09:30 UTC, dvHuni approved these changes, later dismissed

2022-08-19 09:31 UTC, dvHuni approved these changes

2022-08-19 09:41 UTC, kimkyunghun3 approved these changes

2022-08-19 09:42 UTC, merged