Feature/sh/main home
mash-up-kr/GGiriGGiri-iOS pull request #21
Opened 2022-07-03 15:38 UTC by ios-h

# 개요
- 🔗  이슈링크 : https://github.com/mash-up-kr/GGiriGGiri_iOS/issues/11

## 작업 내용
- Git CommitMessage Template 수정
- CompositionalLayout을 이용한 홈 화면 구현 (MockData 표시)

현재 표시되는 뷰들 (버튼, 셀 등) 은 임시로 만들어놓은 뷰입니다!

### 스크린샷
<img width="468" alt="스크린샷 2022-07-04 오전 12 30 46" src="https://user-images.githubusercontent.com/95578975/177046648-17ac7dfc-2981-4c48-b220-831ee3b8d4b3.png">

### 미리보기
![Simulator Screen Recording - iPhone 13 Pro Max - 2022-07-04 at 00 30 58](https://user-images.githubusercontent.com/95578975/177046609-e1796ff2-0e1a-479e-ae80-653d9ce84d4c.gif)

2022-07-03 16:33 UTC, ios-h commented on Projects/App/Sources/Common/Model/LayoutManager.swift
> +}
LayoutManager를 통해 CollectionView의 Item, Group, Header, Section을 구성하도록 했습니다.

2022-07-03 16:34 UTC, ios-h commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +    private let verticalStackView: UIStackView = {
지금은 뷰에 데이터를 표시하기 위해 임시로 StackView에 모든 데이터를 넣어서 구현하였습니다!

2022-07-04 02:19 UTC, dvHuni requested changes
작업량이 많았는데, 수고많았습니다 🙇

2022-07-04 02:19 UTC, szzang-kr commented on Projects/App/Sources/Common/Model/LayoutManager.swift
> +struct LayoutManager {
어떤 Layout을 매니징 하는지 네이밍에서 조금 더 유추 할 수 있으면 좋을 것 같아요.

ex. HomeCollectionViewLayoutManager

2022-07-04 02:19 UTC, szzang-kr commented on Projects/App/Sources/Common/Model/Size.swift
> +struct Size {
마찬가지로 어떤 Size를 의미하는지 명시해주면 좋을것 같아요.

2022-07-04 02:19 UTC, szzang-kr commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +class GitfticonCardCollectionViewCell: UICollectionViewCell {
여기에는 final을 붙이지 않은 이유가 있을까요?

2022-07-04 02:19 UTC, szzang-kr commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +            }
이미지 로드 라이브러리가 있어야 할것 같군요😓 

이슈 남겨주시면 빠르게 적용해보겠습니다.

2022-07-04 02:19 UTC, szzang-kr commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +        verticalStackView.addArrangedSubview(remainingTimeLabel)
Eddy에게 남긴 코멘트와 동일한데요, 중복된 코드를 줄이는 방법으로 `extension`을 사용하는 방법은 어떨까요? (cc. @kimkyunghun3)

2022-07-04 02:19 UTC, szzang-kr commented on Projects/App/Sources/Main/MainCollectionViewDataSource.swift
> +            }
❓cell을 deque하고, 사용하려는 Type으로 캐스팅 하는데 까지 코드가 너무 길어서 작성하기도, 읽기도 힘들것 같네요.

어떻게 줄일수 있을까요?

생각나는 방법을 몇가지 적어보겠습니다. 모두 반영하지 않아도 좋습니다. 생각해보고 의견을 말씀해주세요 😄 

추가적으로 생각나는 방법이 있으면 코멘트 달아주세요 !

1. reuseIdentifier를 cell에 static으로 지정한다.
```swift
String(describing: GifticonDeadLineCollectionViewCell.self) // 기존
GifticonDeadLineCollectionViewCell.reuseIdentifier) // 변경
```

2. `collectionView.dequeueReusableCell(withReuseIdentifier:)` 메소드와 parameter name이 너무 기니까 축약.
 ```swift
collectionView.dequeueReusableCell(withReuseIdentifier:) // 기존
collectionView.dequeueCell(with: ) //변경
```

2022-07-04 02:19 UTC, dvHuni commented on Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
> +        }
한곳에만 SnapKit을 import 해도 다른곳에서는 import 하지 않아도 사용할 수 있습니다.

어떤 이유가 있었는데.. 찾으려고 하니 잘 기억이 안나네요. 😭 

하지만 사용하는 모든 곳에서 명확하게 import를 명시해주는 것이 좋을 것 같습니다.
https://github.com/SnapKit/SnapKit/issues/186

2022-07-04 02:19 UTC, dvHuni commented on Projects/App/Sources/SceneDelegate.swift
> +        window.rootViewController = navigationController
👍

2022-07-04 03:59 UTC, kimkyunghun3 requested changes
고생했습니다!! 👍🌟

2022-07-04 03:59 UTC, kimkyunghun3 commented on Projects/App/Sources/Main/MainViewController.swift
> +class MainViewController: UIViewController {
❓`MainViewController`는 상속의 여지가 있을까요?

2022-07-04 03:59 UTC, kimkyunghun3 commented on Projects/App/Sources/Main/Model/Category.swift
> +enum Category: String, CaseIterable {
❓enum를 따로 파일로 빼신 이유가 있을까요? 이렇게 분리해두면 모든 곳에서 접근이 가능한거 같은데 전역적으로 enum 선언에 대해 의견이 궁금합니다!

2022-07-04 03:59 UTC, kimkyunghun3 commented on Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
> +class CategoryCollectionViewCell: UICollectionViewCell {
❓`Cell`에 `final`를 붙이지 않는 이유가 있을까요?

2022-07-04 03:59 UTC, kimkyunghun3 commented on Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
> +    private func configure() {
❓이곳과 위에 `configure` 메서드 네이밍이 동일한데, `configure`는 정확하게 어떤 것을 만들때 사용하는 네이밍인가요?

2022-07-04 03:59 UTC, kimkyunghun3 commented on Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
> +        if imageUrl.count > 0 {
제 생각에는 Cell은 View라서 로직이 있으면 안된다고 생각합니다. 

❓저도 정확하지는 않지만.. 이곳에 로직이 있는듯 싶은데(ex, 조건문) 이에 대해 어떻게 생각하시나요?

2022-07-04 04:00 UTC, kimkyunghun3 commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +        verticalStackView.addArrangedSubview(remainingTimeLabel)
요것은 저의 마지막 PR를 보시면 `extension` 과 은닉화에 대해 고민해본 것을 보실 수 있습니다! 확인해보세요 :)
https://github.com/mash-up-kr/GGiriGGiri_iOS/pull/20

2022-07-04 04:54 UTC, ios-h commented on Projects/App/Sources/Common/Model/LayoutManager.swift
> +struct LayoutManager {
이후 다른 화면에서도 사용할 일이 있을 것 같아서, `CollectionViewLayoutManager`로 수정했는데 괜찮을까요?

2022-07-04 07:36 UTC, ios-h commented on Projects/App/Sources/Common/Model/Size.swift
> +struct Size {
Size -> CollectionViewConfigureSize로 수정하였습니다!

2022-07-04 07:37 UTC, AhnSangHee commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +class GitfticonCardCollectionViewCell: UICollectionViewCell {
깜빡했네요..😭 추가했습니다 !

2022-07-04 07:38 UTC, ios-h commented on Projects/App/Sources/Main/MainViewController.swift
> +class MainViewController: UIViewController {
`final` 추가하는 것을 깜빡했습니다! 상속의 여지가 없는 클래스에 모두 final 키워드 추가해주었습니다~!

2022-07-04 07:39 UTC, ios-h commented on Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
> +class CategoryCollectionViewCell: UICollectionViewCell {
`final` 추가하는 것을 깜빡했습니다! 상속의 여지가 없는 클래스에 모두 final 키워드 추가해주었습니다~!

2022-07-04 07:42 UTC, ios-h commented on Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
> +        }
SnapKit을 사용하는 모든 곳에서 명시해주도록 수정하였습니다🙂

2022-07-04 07:53 UTC, ios-h commented on Projects/App/Sources/Main/Model/Category.swift
> +enum Category: String, CaseIterable {
카테고리는 이후에도 전체적으로 계속 사용할 여지가 있을 거라고 생각해서 따로 분리해두었습니다! 
근데 생각해보니 Common으로 디렉토리를 변경해야할 것 같아서 Common으로 이동해두었습니다~!

2022-07-04 16:10 UTC, ios-h commented on Projects/App/Sources/Main/MainCollectionViewDataSource.swift
> +            }
기존에 존재하는 메서드의 이름을 축약해서 사용하기보다는 reuseIdentifier를 만드는게 더 낫다고 생각하여 제안해주신 1번 방법으로 모두 수정하였습니다! 😀

2022-07-04 16:15 UTC, ios-h commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +            }
[#23](https://github.com/mash-up-kr/GGiriGGiri_iOS/issues/23) 이슈 추가해두었습니다!

2022-07-04 16:25 UTC, ios-h commented on Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
> +    private func configure() {
`configure()`는 내부 cell에서 private하게 셀을 구성해주는 역할을 하고, `configure(with:)`는 외부에서 데이터를 통해 셀을 구성해주는 역할을 합니다!

2022-07-04 16:50 UTC, ios-h commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +        verticalStackView.addArrangedSubview(remainingTimeLabel)
```swift
extension UIStackView {
    func addArrangedSubviews(with views: [UIView]) {
        views.forEach {
            addArrangedSubview($0)
        }
    }
}
```
요렇게 바꿔보려고 하는데, 의도하신 바가 맞을까요?! @dvHuni @kimkyunghun3

2022-07-04 16:50 UTC, ios-h commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +        verticalStackView.addArrangedSubview(remainingTimeLabel)
```swift
extension UIStackView {
    func addArrangedSubviews(with views: [UIView]) {
        views.forEach {
            addArrangedSubview($0)
        }
    }
}
```
요렇게 바꿔보려고 하는데, 의도하신 바가 맞을까요?!

2022-07-04 16:55 UTC, kimkyunghun3 commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +        verticalStackView.addArrangedSubview(remainingTimeLabel)
제가 말한 의도는 전역으로 extension를 사용하면 모든 곳에서 접근 가능한 것이라 이는 OOP에서 은닉화를 위반한 것이라고 판단했습니다. 그래서 제 PR에서 보시면 사용처에서만 채택해서 사용할 수 있게 프로토콜을 사용해서 은닉화를 하도록 했습니다! PR에서 이야기 나눈것을 한번 봐보시고 이해 안되시면 다시 설명해보겠습니다..!

2022-07-04 17:10 UTC, kimkyunghun3 commented on Projects/App/Sources/Main/Model/Category.swift
> +enum Category: String, CaseIterable {
저는 이 부분도 결국 전역적인 Enum이라고 생각해서 모든 곳에서 사용하지 않는 부분이라면 추후에 사용처에서만 사용할 수 있도록 은닉화를 해주면 좋지 않을까 생각하지만..! 또 이렇게 사용하는 것을 많이 보았기에 다른 요소들과 트레이드오프 생각해서 선택하시면 좋을거같습니다!

2022-07-04 17:10 UTC, ios-h commented on Projects/App/Sources/Common/View/GitfticonCardCollectionViewCell.swift
> +        verticalStackView.addArrangedSubview(remainingTimeLabel)
오옹 이해했습니다! 저는 addArrangedSubview는 StackView에서만 사용 가능한 메서드이고, StackView에 뷰를 추가하려면 반드시 addArrangedSubview가 필요하기 때문에 굳이 은닉화가 필요하지 않다고 생각해서 프로토콜은 사용하지 않았습니다!

2022-07-04 17:17 UTC, ios-h commented on Projects/App/Sources/Main/Model/Category.swift
> +enum Category: String, CaseIterable {
일단 지금은 전역적으로 사용할 여지가 있어서 저렇게 두었지만 추후 사용처가 많지 않다면 은닉화로 변경하는 것을 고려해보도록 하겠습니다~!

2022-07-04 17:52 UTC, ios-h commented on Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
> +        if imageUrl.count > 0 {
저도 동의하는 바입니다! 일단은 이미지 처리 로직을 MainCollectionViewDataSource로 옮겼는데, 추후 ViewModel을 생성하면 ViewModel로 옮기도록 하겠습니다~!

2022-07-04 21:58 UTC, dvHuni commented on Projects/App/Sources/Main/MainCollectionViewDataSource.swift
> +            }
좋습니다~!!

추가적으로 dequeue를 할때마다 as 캐스팅을 해주어야 하는데요, generic을 통해서 간결하게 만들 수 있을 것 같습니다. 해커톤에서 같이 추가해 봅시다 😆

2022-07-04 22:04 UTC, dvHuni approved these changes

2022-07-05 01:02 UTC, kimkyunghun3 approved these changes

2022-07-05 03:04 UTC, merged