[D2] 홈 화면 세부 기능 추가
mash-up-kr/GGiriGGiri-iOS pull request #28
Opened 2022-07-05 17:08 UTC by ios-h

# 개요
- 🔗  이슈링크 : https://github.com/mash-up-kr/GGiriGGiri_iOS/issues/25

# 변경사항

## 작업 내용

- 플로팅 버튼 추가
- 셀 클릭 이벤트 구현
   - 현재는 셀을 클릭하면 로그메시지로 셀의 indexPath.section, indexPath.item이 출력되도록 하였습니다.
- 응모하기 버튼 클릭 시 버튼 타이틀 변경되도록 구현
   - 첫번째 Section (마감 임박) 의 경우, "지금 당장 응모할게요!" 버튼을 클릭하면 "응모완료"로 변경
   - 세번째 Section (기프티콘 응모 리스트) 의 경우, "응모하기" 버튼을 클릭하면 "응모완료"로 변경

### 스크린샷
작업 전|작업 후
---|---
<img width="468" alt="스크린샷 2022-07-04 오전 12 30 46" src="https://user-images.githubusercontent.com/95578975/177046648-17ac7dfc-2981-4c48-b220-831ee3b8d4b3.png">|<img width="468" alt="스크린샷 2022-07-06 오전 2 02 55" src="https://user-images.githubusercontent.com/95578975/177379726-1c27b21c-d111-4950-99a0-e91d705dde2f.png">

### 미리보기
![Simulator Screen Recording - iPhone 13 Pro Max - 2022-07-06 at 02 02 48](https://user-images.githubusercontent.com/95578975/177380342-1092db87-e11b-4456-8fad-0af9efa6220e.gif)

2022-07-05 18:26 UTC, kimkyunghun3 requested changes
고생했습니다🔥

2022-07-05 18:26 UTC, kimkyunghun3 commented on Projects/App/Sources/Main/MainViewController.swift
> +        floatingButton.frame = CGRect(x: view.frame.size.width - 48 - 16,
-48 -16 이 부분이 따로따로 이루어진 이유가 있을까요??

2022-07-05 18:26 UTC, kimkyunghun3 commented on Projects/App/Sources/Common/View/TempButton.swift
> +        self.tintColor = .white
이 부분을 혹시 `method`로 만들지 않고 init에 바로 넣으신 이유가 있나요?

2022-07-05 18:36 UTC, ios-h commented on Projects/App/Sources/Main/MainViewController.swift
> +        floatingButton.frame = CGRect(x: view.frame.size.width - 48 - 16,
x, y에서 앞에 있는 48은 각각 버튼의 width, height 크기를 의미하고, 뒤에 있는 16, 48은 마진을 의미합니다! 명확하게 나누고 싶어서 이렇게 작성했는데, 또 생각해보니 48을 constant로 만들어서 쓰면 더 의미가 명확해질 것 같다는 생각이 드네요!

2022-07-05 18:42 UTC, ios-h commented on Projects/App/Sources/Common/View/TempButton.swift
> +        self.tintColor = .white
딱히 이유는 없는데 메서드로 분리하는게 좋을 것 같네요😅 분리하였습니다!

2022-07-06 00:38 UTC, dvHuni commented on Projects/App/Sources/Main/MainViewController.swift
> +        floatingButton.frame = CGRect(x: view.frame.size.width - 48 - 16,
offset도 마찬가지로 constant로 만들면 좋을 것 같습니다. 😊

2022-07-06 00:51 UTC, dvHuni requested changes
수고하셨습니다 !! 덕분에 진도가 정말 빠른것 같네요 👍

2022-07-06 00:51 UTC, dvHuni commented on Projects/App/Sources/Main/MainCollectionViewDelegate.swift
> +        }
🟡  case 를 int로 분리하게 되면 섹션이 늘어나거나, 코드를 작성하지 않은 인원은 어떤 섹션을 의미하는지 구분하기 힘듭니다.

조금 번거럽더라도 별도의 enum을 만들어 indexPath.section을 wraaping하여 사용하면 협업시에 유리합니다. 😄 

```swift
enum MainColllectionViewSection {
  case main
  case sub
  case unknown

  init(section: Int) {
    switch section: {
      case 0: self = .main
      case 1: self = .sub
      case default: self = .unknown
    }
  }
}

switch MainColllectionViewSection(indexPath.section) {
 case .main:
     Log.info(String(indexPath.section) + String(indexPath.item))
 case .sub:
     Log.info(String(indexPath.section) + String(indexPath.item))
 case .unknown:
     Log.info(String(indexPath.section) + String(indexPath.item))
 }

```

위 코드는 예시입니다. 네이밍이나 syntax는 신경쓰지 않았습니다. 😭

2022-07-06 00:51 UTC, dvHuni commented on Projects/App/Sources/Common/Logger.swift
> +}
디버깅을 위한 log라면 print, debugPrint를 사용하셔도 좋습니다 😃

2022-07-06 02:09 UTC, ios-h commented on Projects/App/Sources/Common/Logger.swift
> +}
Logger를 제거하고 debugPrint를 사용하도록 수정하였습니다! 😃

2022-07-06 02:17 UTC, ios-h commented on Projects/App/Sources/Main/MainCollectionViewDelegate.swift
> +        }
제안해주신대로 기존에 존재하는 MainSection을 이용해서 indexPath.section을 구분하도록 변경했습니다! 😀

2022-07-06 02:27 UTC, kimkyunghun3 approved these changes

2022-07-06 03:04 UTC, dvHuni approved these changes

2022-07-06 03:38 UTC, merged