[D2] 기프티콘 등록 화면 구현
mash-up-kr/GGiriGGiri-iOS pull request #55
Opened 2022-07-15 19:23 UTC by ios-h

# 개요
- 🔗  이슈링크 : https://github.com/mash-up-kr/GGiriGGiri_iOS/issues/35

# 변경사항

## 작업 내용

### 📱 스크린샷1
이전에는 메인 화면의 카테고리 셀들의 너비가 모두 같았는데, 카테고리 셀들의 너비를 글자 수만큼 다이나믹하게 표시되도록 수정하였습니다.
작업 전|작업 후
---|---
<img width="298" alt="스크린샷 2022-07-16 오전 4 18 06" src="https://user-images.githubusercontent.com/95578975/179296030-501f980d-3042-4707-a999-a5b42a6ff2f0.png">|<img width="467" alt="스크린샷 2022-07-16 오전 4 10 50" src="https://user-images.githubusercontent.com/95578975/179295655-476c17c8-70ae-41e1-a4f8-667440dd942e.png">

### 📱 스크린샷2
기프티콘 등록 화면을 구현하였습니다.
<img width="400" alt="스크린샷 2022-07-16 오전 4 10 08" src="https://user-images.githubusercontent.com/95578975/179296379-caa50b30-b35a-44db-a71e-1a6b63f52cd4.png"><img width="400" alt="스크린샷 2022-07-16 오전 4 10 11" src="https://user-images.githubusercontent.com/95578975/179296386-9bb195a5-abf9-4b98-b1d0-d6514f9f2f56.png">

### 미리보기
![Simulator Screen Recording - iPhone 13 Pro Max - 2022-07-16 at 04 10 39](https://user-images.githubusercontent.com/95578975/179295515-8681e4b7-d30c-40ee-b0e1-9dba23749455.gif)

2022-07-15 19:48 UTC, ios-h commented on Projects/App/Sources/Register/CategoryCollectionViewDataSource.swift
> +        if indexPath.item == 6 {
Category 모델은 `전체`, `카페/디저트`, `치킨/배달음식`, `아이스크림`, `편의점`, `패스트푸드`, `상품권`, `기타를` 가지는데 기프티콘 등록 화면에서는 `전체`가 필요 없기 때문에 이러한 로직으로 구성하였습니다.

2022-07-16 18:23 UTC, ios-h commented
# 2022.07.17 추가작업

2022-07-16 18:29 UTC, ios-h commented
# 2022.07.17 추가작업
# 개요
- 🔗  이슈링크 : https://github.com/mash-up-kr/GGiriGGiri_iOS/issues/54

# 변경사항
## 작업 내용
- 앞서 코멘트에 남긴 CategoryCell 관련 오토레이아웃 이슈를 해결하였습니다.
   - item을 만들 때, estimated(1)로 설정한 것과 cell 내부에 있는 라벨의 constraint가 충돌하여 발생했던 문제.
   - estimated에 들어가는 값을 변경하여 이슈 해결
- CollectionViewLayoutManager 메서드 수정
   - configureItem에 inset 파라미터를 제거하였습니다. 여백 관련 설정은 configureGroup의 edgeSpacing 파라미터를 사용하여 설정하도록 수정하였습니다.
   - configureGroup의 itemCount는 사용하지 않기 때문에 제거하였습니다.

### 미리보기
<img width="467" alt="스크린샷 2022-07-17 오전 3 28 51" src="https://user-images.githubusercontent.com/95578975/179367681-82342d53-ead8-49fa-82cb-4f1c98ce18ed.png">

2022-07-17 12:53 UTC, dvHuni requested changes
고생 많았습니다 !! 😆

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/View/RegisterGiftionWrapperView.swift
> +    }
super 가 빠져있습니다!

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/View/RegisterGiftionWrapperView.swift
> +        }
이 부분에서 trailing과 bottom은 어디를 기준으로 잡히는걸까요? 🤔

SuperView를 기준으로 leading, trailing, top, bottom을 동시에 주는 방법일까요?

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/View/RegisterGiftionWrapperView.swift
> +    private(set) var imageView: UIImageView = {
여기는 왜 private(set)일까?

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/View/RegisterGifticonView.swift
> +        scrollView.addSubview(registerButton)
[코드를 줄여쓰는 방법](https://github.com/mash-up-kr/GGiriGGiri_iOS/pull/20/commits/9f3e4e38ebec34468c960c989347daf1e41ee237)도 있을것 같아요!

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/CategoryCollectionViewDataSource.swift
> +        if indexPath.item == 6 {
item의 갯수로 구분하게되면, 이후에 해당 코드를 수정해야 하는 인원은 selina님의 코멘트를 보지 못하면 왜 해당 조건이 필요한지 이해하지 못할 수 있습니다. 😅 

따라서 DataSource를 init 하는 시점에 사용처를 받아서 `CategoryCollectionViewDataSource`가 사용되는 곳으로 분기를 할 수 있을 것 같습니다.
(아이템이 6일때 -> 등록화면에서)

```swift 
final class CategoryCollectionViewDataSource NSObject, UICollectionViewDataSource {
  
  enum Usage {
    case .home
    case .register
  }
  
  private let usage: Usage
  ...
  
  init(_ usage: Usage) {
    self.usage = usage
  }
  
  func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
  ...
  if usage == .register {
    ...
    }
  }
}
```
_네이밍은 예시입니다!_

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/View/RegisterInfoInputView.swift
> +fileprivate class TextInputView: BaseView {
`fileprivate class TextInputView: BaseView`

fileprivate + BaseView인 것 을 보니 해당 RegisterInfoInputView에서만 사용되는 View 이군요! 😄 👍

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
> +        backgroundColor = UIColor(red: 251.0 / 256, green: 251.0 / 256, blue: 251.0 / 256, alpha: 1)
DesignSystem에 있는 컬러를 확인해보고 없는 컬러라면 추가 요청을 해주세요 😅 
(혹시 임시 컬러일까요 😭)

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
> +//        timePickerView.delegate = self
주석 제거 !

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
> +                                         font: .systemFont(ofSize: 14))
Font 도 DesignSystem을 등록해두었습니다.. 사용해주세요 😭

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/CategoryCollectionViewDelegate.swift
> +import Foundation
아직 사용하지 않는 빈 파일이라면 삭제해도 괜찮을것 같습니다. 🤔

2022-07-17 12:53 UTC, dvHuni commented on Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
> +        addSubview(warningMessageLabel)
여기도 마찬가지로 줄여쓸 수 있을 것 같습니다.

2022-07-17 16:53 UTC, kimkyunghun3 requested changes
고생했습니다!

2022-07-17 16:53 UTC, kimkyunghun3 commented on Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
> +    private let ddipTitleLabel = TempLabel(color: .black,
단순히 이 코드 두개를 보았을 때 무슨 차이의 titleLabel인지 구분이 어렵네요!

2022-07-17 16:53 UTC, kimkyunghun3 commented on Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
> +        timePickerView.subviews[1].backgroundColor = .clear
여기에서 1이 의미하는바가 무엇인가요? 바뀌지않는 숫자인가요?

2022-07-17 16:53 UTC, kimkyunghun3 commented on Projects/App/Sources/Register/View/RegisterGifticonView.swift
> +    private let scrollView: UIScrollView = {
세팅이 backgroundColor만 있는데 클로저로 생성해주는 이유가 따로있을까요?

2022-07-18 05:37 UTC, ios-h commented on Projects/App/Sources/Register/View/RegisterGifticonView.swift
> +        scrollView.addSubview(registerButton)
UIView+를 추가해서 코드 중복을 제거했습니다!

```swift
extension UIView {
    func addSubviews(with views: [UIView]) {
        views.forEach {
            addSubview($0)
        }
    }
}
```

2022-07-18 05:40 UTC, ios-h commented on Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
> +        backgroundColor = UIColor(red: 251.0 / 256, green: 251.0 / 256, blue: 251.0 / 256, alpha: 1)
임시 사용 용도였습니다ㅎㅎ 이 코드는 제거했습니다!!!

2022-07-18 05:41 UTC, ios-h commented on Projects/App/Sources/Register/CategoryCollectionViewDelegate.swift
> +import Foundation
삭제하였습니다!

2022-07-18 05:43 UTC, ios-h commented on Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
> +        addSubview(warningMessageLabel)
UIView Extension에 추가한 `addSubviews(with:)` 메소드를 사용하도록 수정하였습니다!

2022-07-18 06:30 UTC, ios-h commented on Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
> +    private let ddipTitleLabel = TempLabel(color: .black,
![스크린샷 2022-07-18 오후 3 23 15](https://user-images.githubusercontent.com/95578975/179454987-54920f74-cd9c-4a79-a1b6-96b9abac0ba8.png)
titleLabel은 사진 제일 위에 있는 "뿌리기 정보"를 나타내는 라벨, ddipTitleLabel은 그 밑의 "마감시간"을 나타내는 라벨이었습니다!




구분을 쉽게 하기 위해서 다음과 같이 네이밍을 수정하였습니다.
![스크린샷 2022-07-18 오후 3 24 42](https://user-images.githubusercontent.com/95578975/179455665-5ccbab7f-62d1-408a-8871-55c49e132a40.png)

2022-07-18 06:32 UTC, ios-h commented on Projects/App/Sources/Register/View/RegisterGifticonView.swift
> +    private let scrollView: UIScrollView = {
이유는 따로 없습니다. 클로저로 생성하는 것을 선호하는 편이라 이렇게 작성하였습니다!

2022-07-18 06:44 UTC, ios-h commented on Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
> +        timePickerView.subviews[1].backgroundColor = .clear
1은 pickerView에서 선택된 영역을 표시합니다! 배경색을 커스텀하기 위해 .clear로 변경해주었습니다!

2022-07-18 14:32 UTC, ios-h commented on Projects/App/Sources/Register/CategoryCollectionViewDataSource.swift
> +        if indexPath.item == 6 {
enum을 다음과 같이 변경하였습니다.

```swift
enum Category: String, CaseIterable {
    case all = "전체"
    case cafe = "카페/디저트"
    case delivery = "치킨/배달음식"
    case icecream = "아이스크림"
    case store = "편의점"
    case fastfood = "패스트푸드"
    case certificate = "상품권"
    case etc = "기타"
    
    static let register: [Category] = Category.allCases.filter { return $0 != Category.all }
}
```

그래서 메인 화면에서는 Category.allCases를 사용하고, 기프티콘 등록 화면에서는 Category.register을 사용하도록 하여 불필요한 로직을 제거하였습니다!

2022-07-18 14:42 UTC, ios-h commented on Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
> +                                         font: .systemFont(ofSize: 14))
요 부분은 모두 폰트를 사용하도록 변경했습니다!! 이슈 추가로 만들어서 다른 뷰들도 모두 폰트 사용하도록 변경하겠습니다😃

2022-07-18 14:45 UTC, dvHuni approved these changes

2022-07-19 00:43 UTC, kimkyunghun3 approved these changes

2022-07-19 01:50 UTC, merged