[D2] 기프티콘 등록 화면 디테일 구현
mash-up-kr/GGiriGGiri-iOS pull request #64
Opened 2022-07-21 07:19 UTC by ios-h

# 개요
- 🔗  이슈링크 : resolve #62 

# 변경사항
## 💻 작업 내용
- 커스텀 이미지 피커 → PHPicker 사용하도록 변경
- 스크롤뷰 내부에 있는 버튼을 밖으로 뺌
- 선택된 사진 가져와서 기프티콘 등록 화면에 표시
- 기프티콘 등록 화면에서 원본 보기 버튼 클릭하면 원본 볼 수 있도록 구현
- 상단 내비게이션 바에 닫기 버튼, 내비게이션 타이틀 추가

## 📱 미리보기
원래는 사진을 선택하면 기프티콘을 분석하는 팝업창이 임시로 떠야하는데, 지금은 임시로 알림창이 뜨도록 구현했습니다.
작업 전|작업 후
---|---
![Simulator Screen Recording - iPhone 13 Pro Max - 2022-07-21 at 16 17 07](https://user-images.githubusercontent.com/95578975/180153296-18ecfddb-a9ca-4740-8696-70e8e9bcf57c.gif)|![Simulator Screen Recording - iPhone 13 Pro Max - 2022-07-21 at 16 14 49](https://user-images.githubusercontent.com/95578975/180153070-6355f6df-1d90-4281-99c7-c95f8d9d8933.gif)

2022-07-21 12:18 UTC, dvHuni approved these changes
수고하셨습니다 !! 코멘트 남겨놓은 내용들은 수정해도 되고 하지 않아도 괜찮습니다 😆

2022-07-21 12:18 UTC, szzang-kr commented on Projects/App/Sources/Main/MainViewController.swift
> +        dismiss(animated: true)
💭 비즈니스 로직은 ViewModel에 둘 수 있을 것 같은데요, 어떻게 두면 좋을지 함께 이야기 해보아용

2022-07-21 12:18 UTC, szzang-kr commented on Projects/App/Sources/Register/GiftionImageViewController.swift
> +        view.backgroundColor = .white
```suggestion
        view.backgroundColor = .ddip(.neutralWhite))
```

designSystem을 사용해주세요 😅

2022-07-21 12:18 UTC, szzang-kr commented on Projects/App/Sources/Register/RegisterGifticonViewController.swift
> +        }).disposed(by: disposeBag)
onNext의 내용은 closure이기 때문에 strong reference를 사용하게되면 reference cycle을 발생시킬 수 있습니다. 😅

2022-07-21 12:29 UTC, ios-h commented on Projects/App/Sources/Register/GiftionImageViewController.swift
> +        view.backgroundColor = .white
흰색의 경우 모두 designSystem을 사용하도록 변경했습니다~!

2022-07-21 17:07 UTC, kimkyunghun3 requested changes
고생했습니다~~

2022-07-21 17:07 UTC, kimkyunghun3 commented on Projects/App/Sources/Main/MainViewController.swift
> +            self.presentPhotoPicker()
self 사용에 대해서는 통일성을 유지하면 좋을거같습니다!

2022-07-21 17:07 UTC, kimkyunghun3 commented on Projects/App/Sources/Register/View/RegisterGifticonView.swift
> +            $0.top.equalTo(scrollView.snp.bottom).offset(46)
요렇게 숫자로 대입하면 여러 기기에서도 대응이 가능한가요?

2022-07-21 17:07 UTC, kimkyunghun3 commented on Projects/App/Sources/Main/MainViewController.swift
> +        if let itemProvider = results.first?.itemProvider, itemProvider.canLoadObject(ofClass: UIImage.self) {
itemProvider가 무엇을 말하는걸까요? 이름을 보았을 떄 정확히 어떤 역할인지 파악이 어렵네요!

2022-07-21 17:16 UTC, ios-h commented on Projects/App/Sources/Main/MainViewController.swift
> +        if let itemProvider = results.first?.itemProvider, itemProvider.canLoadObject(ofClass: UIImage.self) {
itemProvider는 인스턴스 프로퍼티로 [여기](https://developer.apple.com/documentation/photokit/phpickerresult/3606600-itemprovider)를 보시면 자세하게 보실 수 있습니다! 간략하게 말씀해드리자면 선택된 asset을 representation하는 역할을 합니다. 애플의 공식 예제 프로젝트도 itemProvider로 네이밍을 했기에 저도 itemProvider라고 네이밍했습니다!

2022-07-22 07:39 UTC, ios-h commented on Projects/App/Sources/Register/RegisterGifticonViewController.swift
> +        }).disposed(by: disposeBag)
코멘트 달아주신 부분 수정하여 반영했습니다!!!

2022-07-22 07:41 UTC, szzang-kr commented on Projects/App/Sources/Register/RegisterGifticonViewController.swift
> +        }).disposed(by: disposeBag)
@ios-h

[내비게이션 버튼 탭 이벤트에 reference cycle 제거 ](https://github.com/mash-up-kr/GGiriGGiri_iOS/pull/64/commits/457376476394cc5b7c915aec131439b7da436694)
[delegate를 weak var로 변경 ](https://github.com/mash-up-kr/GGiriGGiri_iOS/pull/64/commits/0d8101a3f69cdd090b92bbed07a8e7d459a0dec0) 두 커밋에서 확인 완료했습니다 😆

2022-07-22 08:44 UTC, ios-h commented on Projects/App/Sources/Register/View/RegisterGifticonView.swift
> +            $0.top.equalTo(scrollView.snp.bottom).offset(46)
넵! 스크롤뷰는 스크롤뷰만의 높이를 갖고, 높이가 정해진 스크롤뷰로부터의 offset 만큼 상수를 주는 것이기 때문에 기기와 상관 없이 대응 가능합니다!😀

2022-07-23 00:00 UTC, kimkyunghun3 approved these changes

2022-07-23 04:34 UTC, merged