[D2] ListCardView, DeadLineView UI 구현
mash-up-kr/GGiriGGiri-iOS pull request #68
Opened 2022-07-24 04:57 UTC by kimkyunghun3

# 개요
- 🔗  이슈링크 : #5 

## 작업 내용
ListCardView UI 구현 ( Font, Color는 리베이스를 아직 하지 못해서 적용이 되지 않았는데 리베이스 해야할지 의논 후 적용하겠습니다 )
DeadLineView UI 구현

### 스크린샷

<img src ="https://user-images.githubusercontent.com/52434820/180615607-473e389e-3e45-4426-b0ef-fc1086d9024b.png" width ="400">|<img src ="https://user-images.githubusercontent.com/52434820/180632118-da295fe3-83fc-4e4f-b227-7e7ad36e62cf.png" width ="400">|

2022-07-24 07:01 UTC, ios-h requested changes
뷰가 복잡해서 구현하기 까다로웠을텐데 고생 많으셨습니다! 👍👍

2022-07-24 07:01 UTC, AhnSangHee commented on Projects/DesignSystem/Sources/Component/Button/DDIPCardListButton.swift
>          self.titleLabel?.font = .systemFont(ofSize: 14)
🔴 디자인 시스템 폰트를 사용해주시면 감사하겠습니다!🙂

2022-07-24 07:01 UTC, AhnSangHee commented on Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
> +        expirationLabel.font = UIFont.systemFont(ofSize: 12)
🔴 요기도 디자인 시스템 폰트를 사용해주세요! 😀

2022-07-24 07:01 UTC, AhnSangHee commented on Projects/DesignSystem/Sources/Component/Extension/StackView+.swift
> +//  StackView+.swift
🟡 별건 아니지만 `StackView+` 대신 `UIStackView+`로 네이밍해도 좋을 것 같습니다!

2022-07-24 07:01 UTC, AhnSangHee commented on Projects/DesignSystem/Sources/Component/Extension/UIView+sugar.swift
> +        caShapeLayer.lineDashPattern = [2,4]
❓ [2, 4]에서 2가 페인팅된 세그먼트, 4가 페인팅되지 않은 세그먼트라고 생각이 되는데 혹시 맞을까요?!

만약 맞다면! 저희 피그마를 보면 점선이 페인팅된 세그먼트와 페인팅되지 않은 세그먼트가 동일한 너비를 갖는 걸로 알고 있는데 [2, 4]가 아닌 [2, 2] 또는 [4, 4]로 값을 줘야하지 않나 하는 생각이 듭니다!!

2022-07-24 07:01 UTC, AhnSangHee commented on Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
> +    private let viwer: DDIPListViewer
🔴 오타가 있는 것 같아요!
```suggestion
    private let viewer: DDIPListViewer
```

2022-07-24 07:01 UTC, AhnSangHee commented on Projects/DesignSystem/Sources/Component/ListViwer/DDIPListViewer.swift
>      private let viwerStackView: UIStackView = {
🔴 오타가 있어요!!
```suggestion
    private let viewerStackView: UIStackView = {
```

2022-07-24 07:01 UTC, AhnSangHee commented on Projects/DesignSystem/Sources/Component/ListViwer/DDIPListViewer.swift
>      private var viewerLabel: UILabel = UILabel()
🟡 개인적으로 `DDIPListViewer`라는 네이밍이 무엇인지 알기 힘든 것 같아요! 응모자수를 나타내는 뷰라면 `DDipApplyViewer`와 같은 네이밍은 어떨까 조심스레 제안해봅니당!

2022-07-24 07:06 UTC, ios-h commented on Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
> +    public let expirationLabel = UILabel()
❓ `유효기간` 이라는 라벨은 고정되어있고, 실제로 받는 유효기간 날짜 데이터는 모두 다르기 때문에 `유효기간` 자체를 표시하는 라벨과 유효기간 날짜를 받는 라벨의 2가지 라벨이 있어야 하지 않나 하는 생각이 듭니다..!!

2022-07-24 07:08 UTC, ios-h commented on Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
> +    public let expirationLabel = UILabel()
❓ `유효기간` 이라는 레이블은 고정되어있고, 실제로 받는 유효기간 날짜 데이터는 모두 다르기 때문에 `유효기간` 자체를 표시하는 레이블과 유효기간 날짜를 받는 레이블의 2가지 레이블이 있어야 하지 않나 하는 생각이 듭니다..!!

2022-07-24 07:09 UTC, ios-h commented on Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
> +    public let expirationLabel = UILabel()
❓요기도 앞에 코멘트 달았던 것과 동일하게, 2가지 레이블이 있어야 하지 않나 하는 생각이 듭니다!

2022-07-24 07:11 UTC, ios-h commented on Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
> +    public let spaceLeftView: UIView = {
🟡  `spaceLeftView`, `spaceRightView` 라는 네이밍을 처음 보면 무엇인지 이해하기 어려울 것 같아요!! `leftSemicircleView`, `rightSemicircleView`와 같이 더 명확한 네이밍은 어떨까 하는 제안을 조심스레 드려봅니다 ! 😮

2022-07-24 07:57 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/ListViwer/DDIPListViewer.swift
>      private let viwerStackView: UIStackView = {
앗 수정했습니다 확인감사합니다 👍

2022-07-24 07:57 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/ListViwer/DDIPListViewer.swift
>      private var viewerLabel: UILabel = UILabel()
말씀들어보니 조금 더 applyViewer가 더 명확한거같네요! 다 수정했습니다~~

2022-07-24 07:58 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
> +    private let viwer: DDIPListViewer
수정했습니다 감사합니다 👍

2022-07-24 07:58 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/Extension/StackView+.swift
> +//  StackView+.swift
넵 더 명확하게 바꾸었습니다!!!

2022-07-24 08:07 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/Extension/UIView+sugar.swift
> +        caShapeLayer.lineDashPattern = [2,4]
앗 확인해보니 3.5씩 되어있어서 3.5 3.5로 수정했습니다 감사합니다!

2022-07-24 08:23 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
> +    public let spaceLeftView: UIView = {
조금 더 명확하게 하려고 semiCircleSpaceLeftView, semiCircleSpaceRightView로 변경했습니다! 조언 감사합니다 :)

2022-07-24 08:29 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/Button/DDIPCardListButton.swift
>          self.titleLabel?.font = .systemFont(ofSize: 14)
이 부분은 다른 컴포넌트도 적용해야해서 PR 이후 머지되면 전체적으로 적용해서 다시 PR 올리겠습니다!

2022-07-24 08:29 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
> +        expirationLabel.font = UIFont.systemFont(ofSize: 12)
이 부분은 다른 컴포넌트도 적용해야해서 PR 이후 머지되면 전체적으로 적용해서 다시 PR 올리겠습니다!

2022-07-24 08:54 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
> +    public let expirationLabel = UILabel()
유효기간이라는 단어가 고정으로 되어있다면 추가로 라벨을 만들지 않아도 고정값으로 넘어주면 괜찮을 것 같습니다! 만약 이 값이 변동성이 있다면 라벨을 추가로 해야겠지만 현재 기획에서는 변동성이 없어보여서 일단 고정으로 넣어두겠습니다!!

2022-07-24 08:57 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
> +    public let expirationLabel = UILabel()
유효기간이라는 단어가 고정으로 되어있다면 추가로 라벨을 만들지 않아도 고정값으로 넘어주면 괜찮을 것 같습니다! 만약 이 값이 변동성이 있다면 라벨을 추가로 해야겠지만 현재 기획에서는 변동성이 없어보여서 일단 고정으로 넣어두겠습니다!!

2022-07-24 10:03 UTC, dvHuni approved these changes
수고하셨습니다. 😄

2022-07-24 10:03 UTC, szzang-kr commented on Projects/DesignSystem/Sources/Component/Extension/UIStackView+.swift
> +}
UIView의 addSubView의 경우는 protocol을 채택해서 은닉화를 했는데,

UIStackView의 경우는 은닉화를 사용하지 않았네요. 어떤 이유때문일까요?

2022-07-24 10:03 UTC, szzang-kr commented on Projects/DesignSystem/Sources/Component/Extension/UIView+sugar.swift
> +        let cgPoint = [CGPoint(x: self.bounds.minX, y: 0), CGPoint(x: 310, y: 0)]
🟡 point를 고정으로 그리게 해뒀는데, 공통적으로 사용하는 method인 만큼 주입받아서 그리는 방식이 더 좋을것 같아요.

```swift
func createDottedLine(endPoint: CGPoint = .zero, end width: CGFloat, color: CGColor)
```

2022-07-25 02:12 UTC, AhnSangHee approved these changes

2022-07-25 03:52 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/Extension/UIStackView+.swift
> +}
먼저 StackView를 protocol로 은닉화 하려고 했는데, 사용처의 Self가 UIView여서 이 프로토콜을 채택하더라도 메서드를 사용할 수 없는 이슈가 있습니다.

그리고 두번째로는 StackView라고 범위를 한정지었기 때문에 StackView에서만 사용할 수 있으며 StackView의 성격상 여러 개의 뷰들을 더하기 때문에 이 메서드를 모두 사용할 것이라고 생각했습니다. 그리하여 protocol를 사용하지 않더라도 사용처의 범위가 좁아져 있기에 괜찮다고 판단했는데, 그럼에도 불구하고 채택하는 방향을 해야할까요?

2022-07-25 04:27 UTC, dvHuni commented on Projects/DesignSystem/Sources/Component/Extension/UIStackView+.swift
> +}
굳이 채택하지 않아도 괜찮을것 같습니다.
어떠한 이유가 있는지 궁금했습니다. 😄

추가적으로 말씀해주신 첫번째 이슈를 해결하기 위해서는 UIStackView를 상속하고, protocol을 채택하는 새로운 BaseStackView를 만들어 사용해야합니다.

```swift
protocol AddArrangedSubviewsable where Self: UIStackView { }
class BaseStackView: UIStackView, AddArrangedSubviewsable { }
```

2022-07-25 04:53 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/Extension/UIStackView+.swift
> +}
아하 이렇게 해결할 수 있겠군요! 좋은 의견 감사합니다!!

2022-07-26 14:13 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/Extension/UIView+sugar.swift
> +        let cgPoint = [CGPoint(x: self.bounds.minX, y: 0), CGPoint(x: 310, y: 0)]
이 부분에 대해서 주입받아서 해보았지만 결국 상위뷰에 대해 정확한 width를 확인하지 못해서
draw 메서드를 활용해서 DottedLine과 SpaceView를 구현 변경했습니다.
이렇게 하니 width를 억지로 만드는 것이 아니라, 동적으로 처리해줄 수 있어서 더 적절한 구현방식인듯싶습니다!

한번 확인해주시고 수정이 필요하다면 말씀해주세요 👍

2022-07-26 22:03 UTC, dvHuni approved these changes

2022-07-27 00:23 UTC, merged