[D2] CountdownCardView 구현
mash-up-kr/GGiriGGiri-iOS pull request #79
Opened 2022-07-30 08:01 UTC by kimkyunghun3

# 개요
- 🔗  이슈링크 : #5 

# 변경사항

## 작업 내용
- CountdonwCardView 구현 ( 사용처에 맞게 로직 변경은 내일 모든 곳에서 함께 적용하겠습니다 )
- timeLabel에서 숫자마다 사이즈가 달라서 가장 긴 숫자의 width를 고정으로 주어서 해결했습니다.

### 스크린샷
| border 적용 시 | border 없을 시|
|:---:|:---:|
|<img src ="https://user-images.githubusercontent.com/52434820/181885166-e27724cd-d2cf-499f-a0a4-e1efb593f3aa.png" width ="200">|<img src ="https://user-images.githubusercontent.com/52434820/181885322-90dfc3e0-6023-464b-817f-b7d43a82a270.png" width ="200">|

2022-07-30 11:42 UTC, dvHuni requested changes
수고하셨습니다 🫡

2022-07-30 11:42 UTC, dvHuni commented on Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardViewStyle.swift
> +    public let iconImage: String
이미지는 string이 아닌 DDIPAsset.name을 받으면 좋을것 같아요!

이미지는 어차피 DesignSystem의 Asset으로만 사용하니까요!
(enum인데 대문자로 시작하지 않네요.. 나중에 고쳐놓겠습니다 😭)

2022-07-30 11:42 UTC, dvHuni commented on Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
> +        stackView.alignment = .fill
마찬가지로 지정하지 않아도 될것같습니다.

2022-07-30 11:42 UTC, dvHuni commented on Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
> +        stackView.distribution = .fill
alignment와 distrubution의 .fill은 기본속성이므로 따로 지정하지 않아도 될것같습니다.

https://developer.apple.com/documentation/uikit/uistackview/1616243-alignment

https://developer.apple.com/documentation/uikit/uistackview/1616233-distribution

2022-07-30 12:20 UTC, ios-h approved these changes
수고하셨습니다👍

2022-07-30 12:20 UTC, ios-h commented on Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
> +        label.text = "응모 마감까지"
❓ 이 라벨은 내용이 바뀔 일이 없지 않나요?! `public`으로 하신 이유가 궁금합니다!

2022-07-31 07:51 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
> +        stackView.distribution = .fill
아하! 맞네요!! 제거하겠습니다!

2022-07-31 08:01 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
> +        stackView.alignment = .fill
넵 수정했습니다!

2022-07-31 08:04 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
> +        label.text = "응모 마감까지"
네 바뀔일이 없네요! private으로 하는게 더 적절한거같습니다 바꿨습니다~

2022-07-31 08:10 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardViewStyle.swift
> +    public let iconImage: String
넵넵! 타입 변경해서 반영했습니다!!!

2022-07-31 08:20 UTC, dvHuni approved these changes

2022-07-31 08:28 UTC, merged