[DA] CountdownTimer 작성 및 적용
mash-up-kr/GGiriGGiri-iOS pull request #88
Opened 2022-08-01 12:52 UTC by dvHuni

# 개요
- 🔗  이슈링크 : #87 

# 변경사항

## 작업 내용

* Date를 받아 카운트 다운을 하는 타이머를 구현하였습니다.
* 먼저 응모하기 화면에 타이머를 적용하였습니다.

### 미리보기

작업 전

https://user-images.githubusercontent.com/39300449/182151856-56d1ebde-e772-4a75-bf8e-d9990808345d.mp4

작업 후

https://user-images.githubusercontent.com/39300449/182151567-5a796f89-26f5-4ea7-957a-d0ed7c9a8fa9.mp4

2022-08-02 14:15 UTC, namsoo5 commented
LGTM🐳

2022-08-03 07:27 UTC, kimkyunghun3 requested changes
타이머 고생하셨습니다!

2022-08-03 07:27 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
> +    // TODO: CTAButton Update Logic 추가해야함
요거는 제꺼 추가해서 나중에 합치면 될거같습니다!

2022-08-03 07:27 UTC, kimkyunghun3 commented on Projects/DesignSystem/Sources/CountDownTimer/DDIPCountDownTimer.swift
> +                self?.desrecase()
요거 스펠링이 `decrease` 로 바꾸어야할거같습니다!

2022-08-03 10:21 UTC, dvHuni commented on Projects/DesignSystem/Sources/CountDownTimer/DDIPCountDownTimer.swift
> +                self?.desrecase()
https://github.com/mash-up-kr/GGiriGGiri_iOS/pull/88/commits/a344229731144f13e4985d7a7d017bcdc9e3a82b 커밋에서 수정했습니다

2022-08-03 10:37 UTC, ios-h approved these changes
고생하셨습니다아👍

2022-08-03 10:39 UTC, kimkyunghun3 approved these changes

2022-08-03 10:41 UTC, merged